# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    send_confirmation_mail_handler:
        class: AppBundle\Command\SendConfirmationMailHandler
        arguments:
            - "@logger"
        tags:
            #- { name: command_handler, handles: AppBundle\Command\SendConfirmationMail }
            - { name: asynchronous_command_handler, handles: AppBundle\Command\SendConfirmationMail }

    send_confirmation_mail_console_command:
        class: AppBundle\ConsoleCommand\SendConfirmationMailCommand
        arguments:
            - "@command_bus"
        tags:
            - { name: console.command }

    doctrine_reconnect_command_bus_middleware:
        class: AppBundle\Middleware\DoctrineReconnectMiddleware
        arguments:
            - "@doctrine.dbal.default_connection"
            - "@logger"
        public: false
        tags:
            - { name: asynchronous_command_bus_middleware, priority: 1001 }

    logging_command_bus_middleware:
        class: AppBundle\Middleware\LoggingMiddleware
        arguments:
            - "@logger"
        public: false
        tags:
            - { name: asynchronous_command_bus_middleware, priority: -1001 }