# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    send_confirmation_mail_handler:
        class: AppBundle\Command\SendConfirmationMailHandler
        arguments:
            - "@logger"
        tags:
            - { name: command_handler, handles: AppBundle\Command\SendConfirmationMail }

    send_confirmation_mail_console_command:
        class: AppBundle\ConsoleCommand\SendConfirmationMailCommand
        arguments:
            - "@command_bus"
        tags:
            - { name: console.command }